### ISSUE TITLE
Trying to register a new user results in a 500 server error and SQL logic error

### ISSUE THREAD

**Issue by scottchiefbaker** [jabberd2/jabberd2#187]
When I try and register a new user Pidgin reports a 500 Server error and my logs show this:

```
Aug 22 10:24:58 perturb jabberd/c2s[17138]: [16] [65.182.224.3, port=36144] connect
Aug 22 10:25:01 perturb jabberd/c2s[17138]: sqlite (authreg): SQL logic error
Aug 22 10:25:01 perturb jabberd/c2s[17138]: [16] [65.182.224.3, port=36144] disconnect jid=unbound, packets: 2, bytes: 352
```

How do I troubleshoot this further? I assume something in corrupt in my database?

**Comment by gdt** [comment]
Check the database ownership and permissions.

**Comment by scottchiefbaker** [comment]
I changed the permissions to 777 thinking that was the issue, and I still get the error. Here are my current permissions:

```
:ls -lsa sqlite.db
272 -rwxrwxrwx 1 root root 278528 Aug 22 10:20 sqlite.db
```

What should it be? The directory is owned by jabber.jabber

**Comment by gdt** [comment]
Hard to say without knowing your setup, but generally 600 and owned by
the same uid that jabberd runs as, or maybe 660 and root owned and the
group that jabberd runs as.  The point is that the jabberd process can
read and write and basically nothing else.

So with 777, it's more or less proven that it's not a permission error
(more or less because until the bug is found, I am reluctant to believe
anything 100%).

So I think you have arrived at having to rebuild jabberd  with debugging
turned on, and turning up logging, and then maybe adding logging.

Also, I keep trying to reply by email.  This should not be an issue on github, but just discussion on the mailinglist, because it's reasonably likely not a bug in jabberd.

**Comment by scottchiefbaker** [comment]
I changed permissions to this and restarted jabber and now it's happy?

```
276 -rwxrwxrwx  1 jabber jabber 282624 Aug 22 16:57 sqlite.db
```

I'm good now.
